-- MySQL Script generated by MySQL Workbench
-- 2019년 03월 23일 (토) 오후 07시 14분 43초
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema capstone02
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema capstone02
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `capstone02` DEFAULT CHARACTER SET utf8 ;
USE `capstone02` ;

-- -----------------------------------------------------
-- Table `capstone02`.`UserLogin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capstone02`.`UserLogin` (
  `UserID` INT NOT NULL,
  `UserName` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`UserID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `capstone02`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capstone02`.`User` (
  `UserID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `DOB` DATE NULL,
  `Email` VARCHAR(45) NULL,
  `PhoneNumber` VARCHAR(45) NULL,
  PRIMARY KEY (`UserID`),
  CONSTRAINT `fk_User_1`
    FOREIGN KEY (`UserID`)
    REFERENCES `capstone02`.`UserLogin` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `capstone02`.`Diary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capstone02`.`Diary` (
  `UserID` INT NOT NULL,
  `DateRegistered` TIMESTAMP NULL,
  `Contents` VARCHAR(45) NULL,
  PRIMARY KEY (`UserID`),
  CONSTRAINT `fk_Diary_1`
    FOREIGN KEY (`UserID`)
    REFERENCES `capstone02`.`User` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `capstone02`.`BloodGlucose`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capstone02`.`BloodGlucose` (
  `UserID` INT NOT NULL,
  `DateRegistered` TIMESTAMP NULL,
  `Value` INT NULL,
  PRIMARY KEY (`UserID`),
  CONSTRAINT `fk_BloodGlucose_1`
    FOREIGN KEY (`UserID`)
    REFERENCES `capstone02`.`User` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `capstone02`.`Medication`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capstone02`.`Medication` (
  `UserID` INT NOT NULL,
  `DateRegistered` TIMESTAMP(3) NULL,
  `MedicationName` VARCHAR(45) NULL,
  `MedicationDose` VARCHAR(45) NULL,
  PRIMARY KEY (`UserID`),
  CONSTRAINT `fk_Medication_1`
    FOREIGN KEY (`UserID`)
    REFERENCES `capstone02`.`User` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `capstone02`.`Activity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capstone02`.`Activity` (
  `UserID` INT NOT NULL COMMENT '					',
  `ActivityName` VARCHAR(45) NULL,
  `DateRegistered` TIMESTAMP NULL,
  PRIMARY KEY (`UserID`),
  CONSTRAINT `fk_Activity_1`
    FOREIGN KEY (`UserID`)
    REFERENCES `capstone02`.`User` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `capstone02`.`Meal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capstone02`.`Meal` (
  `UserID` INT NOT NULL,
  `DateRegistered` TIMESTAMP NULL,
  `Contents` VARCHAR(45) NULL,
  PRIMARY KEY (`UserID`),
  CONSTRAINT `fk_Meal_1`
    FOREIGN KEY (`UserID`)
    REFERENCES `capstone02`.`User` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `capstone02`.`Sentiment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capstone02`.`Sentiment` (
  `SentimentID` INT NOT NULL,
  PRIMARY KEY (`SentimentID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `capstone02`.`SentimentAnalysis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capstone02`.`SentimentAnalysis` (
  `UserID` INT NOT NULL COMMENT '	',
  `DateRegistered` TIMESTAMP NULL,
  `SentimentID` INT NULL,
  PRIMARY KEY (`UserID`),
  INDEX `fk_SentimentAnalysis_1_idx` (`SentimentID` ASC),
  CONSTRAINT `fk_Sentiment_1`
    FOREIGN KEY (`UserID`)
    REFERENCES `capstone02`.`User` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SentimentAnalysis_1`
    FOREIGN KEY (`SentimentID`)
    REFERENCES `capstone02`.`Sentiment` (`SentimentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
